In [0]:
from __future__ import division
import numpy as np
import scipy
import math

**Затраты и объемы**

In [0]:
C_A = np.array([[30, 40, 70, 60], [80, 50, 30, 40]]) #затраты на транспортировку 1-ого вида сырья на предприятия D1, D2
C_B = np.array([[40, 80, 80], [60, 70, 40]]) #затраты на траспортировку 2-ого вида сырья не предприятия D1, D2

b_ub_A = np.array([220, 240, 140, 200]) #ограничения в неравенствах
b_ub_B = np.array([50, 60, 70])
b_eq = np.array([1000, 1200, 1500, 2000, 0, 0]) #ограничения в равенствах

In [0]:
C_AB = np.concatenate((C_A, C_B), axis = None) #все затраты на транспортировку сырья на предприятия
print(C_AB)

[30 40 70 60 80 50 30 40 40 80 80 60 70 40]


In [0]:
ksi = np.array([96,48]) #коэффициент возле объемов
fm = [1382400] #свободный член
print(ksi)

[96 48]


In [0]:
C_d1 = np.append((ksi[0] * np.array([[10, 10, 10, 10]])), ksi[1]*np.array([8, 8, 8, 8])) 
C_d2 = np.append((ksi[0] * np.array([[40, 40, 40]])), ksi[1]*np.array([40, 40, 40]))
print(C_d1)
#print(C_d2)

C_d = np.concatenate((C_d1, C_d2), axis = None) #затраты на обработку сырья на двух предприятиях
print(C_d)

[960 960 960 960 384 384 384 384]
[ 960  960  960  960  384  384  384  384 3840 3840 3840 1920 1920 1920]


In [0]:
C_ABD = C_AB + C_d
print(C_ABD) #затраты на добычу,транспортировку и обработку сырья

[ 990 1000 1030 1020  464  434  414  424 3880 3920 3920 1980 1990 1960]


In [0]:
C_D1_E = np.array([4, 4, 10, 8]) #затраты на перевозку продукции с первого предприятия на базы E
C_D2_E = np.array([8, 3, 6, 5]) #затраты на перевозку продукции со второго предприятия на базы Е


C_D_E = np.concatenate((C_D1_E, C_D2_E), axis = None) #все затраты на перевозку к базам 
print(C_D_E) 

[ 4  4 10  8  8  3  6  5]


In [0]:
C = np.append(C_ABD, C_D_E)
print(C) #все коэффициенты целевой функции

[ 990 1000 1030 1020  464  434  414  424 3880 3920 3920 1980 1990 1960
    4    4   10    8    8    3    6    5]


**Ограничения**

In [0]:
b_ub = np.concatenate((b_ub_A, b_ub_B), axis = None)


In [0]:
A_ub_A = np.array([[1, 0, 0, 0, 1, 0, 0, 0],  #коэффициенты для переменных в неравенствах для X
                  [0, 1, 0, 0, 0, 1, 0, 0], 
                  [0, 0, 1, 0, 0, 0, 1, 0], 
                  [0, 0, 0, 1, 0, 0, 0, 1],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0]])
A_ub_B = np.array([[0, 0, 0, 0, 0, 0],        #коэффициенты для переменных в неравенствах для Y
                  [0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0],
                  [1, 0, 0, 1, 0, 0],
                  [0, 1, 0, 0, 1, 0],
                  [0, 0, 1, 0, 0, 1]])

A_ub_Z = np.zeros([7,8])


**Общая матрица коэффициентов для неравенств**

In [0]:
A_ub = np.concatenate((A_ub_A, A_ub_B, A_ub_Z), axis=1)  
print(A_ub)

[[1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


***Найдём такую же матрицу для равенств***

In [0]:
A_eq_XY = np.zeros([4,14])                   
A_eq_z = np.array([[1, 0, 0, 0, 1, 0, 0, 0], 
                  [0, 1, 0, 0, 0, 1, 0, 0], 
                  [0, 0, 1, 0, 0, 0, 1, 0],  
                  [0, 0, 0, 1, 0, 0, 0, 1]])  #коэффициенты для переменных в равенствах для Zkj

A_eq_1 = np.concatenate((A_eq_XY,A_eq_z), axis=1) #первые 4 ограничения в равенствах
#print(A_eq) 



***Определим коэффициенты для объемов***

In [0]:
Z1 = np.array([[10, 10, 10, 10, 0, 0, 0, 0, 40, 40, 40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

Z2 = np.array([[0, 0, 0, 0, 8, 8, 8, 8, 0, 0, 0, 40, 40, 40, 0, 0, 0, 0, 0, 0, 0, 0]]) 


***Введем коэффициенты для продукции***

In [0]:
A_Z1 = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0]) #коэффициенты для ограничений 
A_Z2 = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1]) 


A_eq_Z1 = A_Z1-Z1 #общие коэффициенты, при переносе всех переменных в левую часть
A_eq_Z2 = A_Z2-Z2
#print(A_eq_Z1) 

A_eq_Z = np.concatenate((A_eq_Z1, A_eq_Z2), axis = 0)
print(A_eq_Z)

[[-10 -10 -10 -10   0   0   0   0 -40 -40 -40   0   0   0   1   1   1   1
    0   0   0   0]
 [  0   0   0   0  -8  -8  -8  -8   0   0   0 -40 -40 -40   0   0   0   0
    1   1   1   1]]


**Общая матрица коэффициентов для равенств**

In [0]:
A_eq = np.concatenate((A_eq_1, A_eq_Z), axis=0) 
print(A_eq)

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    1.   0.   0.   0.   1.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   1.   0.   0.   0.   1.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   1.   0.   0.   0.   1.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   1.   0.   0.   0.   1.]
 [-10. -10. -10. -10.   0.   0.   0.   0. -40. -40. -40.   0.   0.   0.
    1.   1.   1.   1.   0.   0.   0.   0.]
 [  0.   0.   0.   0.  -8.  -8.  -8.  -8.   0.   0.   0. -40. -40. -40.
    0.   0.   0.   0.   1.   1.   1.   1.]]


***Имеем***

In [0]:
print(C)
print(A_ub)
print(b_ub)
print(A_eq)
print(b_eq)

[ 990 1000 1030 1020  464  434  414  424 3880 3920 3920 1980 1990 1960
    4    4   10    8    8    3    6    5]
[[1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
[220 240 140 200  50  60  70]
[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    1.   0.   0.   0.   1.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   1.   0.   0.   0.   1.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   1.   0.   0.   0.   1.   0.]
 [  0.   0.   0.   0.   0.  

In [0]:
from scipy.optimize import linprog
res = linprog(C, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, 
              method='simplex', 
              options={"disp": True}, 
              callback = lambda *x, **kwargs:"tableau" )

print(res)

Optimization terminated successfully.
         Current function value: 311575.000000
         Iterations: 22
     con: array([0., 0., 0., 0., 0., 0.])
     fun: 311575.0
 message: 'Optimization terminated successfully.'
     nit: 22
   slack: array([220. , 240. , 140. , 200. ,   0. ,  37.5,   0. ])
  status: 0
 success: True
       x: array([   0. ,    0. ,    0. ,    0. ,    0. ,    0. ,    0. ,    0. ,
          0. ,    0. ,    0. ,   50. ,   22.5,   70. ,    0. ,    0. ,
          0. ,    0. , 1000. , 1200. , 1500. , 2000. ])


In [0]:
V1_Ch = np.dot(res.get('x')[0:22], Z1[0])
V2_Ch = np.dot(res.get('x')[0:22], Z2[0])

In [0]:
Xvar = np.array([[0, 1],
                 [0, 1],
                 [0, 1],
                 [0, 1],
                 [0, 1],
                 [0, 1],
                 [0, 1],
                 [0, 1],
                 [0, 1],
                 [0, 1],
                 [0, 1],
                 [48, 50],
                 [21, 23],
                 [68, 70],
                 [0, 1],
                 [0, 1],
                 [0, 1],
                 [0, 1],
                 [998, 1000],
                 [1198, 2000],
                 [1498, 1500],
                 [1998, 2000]])

In [0]:
class PAV():
    def __init__(self, cost, A_ub, b_ub, Xvar, A_eq=None, b_eq=None):
        self.cost = cost
        self.f = 0
        self.A_ub = A_ub
        self.b_ub = b_ub
        self.A_eq = A_eq
        self.h = b_eq
        self.Xvar = Xvar
        self.W1_flag = 0
        self.W2_flag = 1
        
    
    
    def max_or_min_W1(self, i, j, mode, flag=0):
    # flag==0 :j
    # flag==1 j+1:
      if (flag):
          return [np.max(self.Xvar[j+1+t]) if self.A_ub[i][j+1+t] > 0 else mode(self.Xvar[j+1+t]) for t in range(len(self.A_ub[i,j+1:]))]
      else: 
          return [np.max(self.Xvar[t]) if self.A_ub[i][t] > 0 else mode(self.Xvar[t]) for t in range(len(self.A_ub[i,:j]))]

    def Ax(self, i, j, mode=None):
      return self.A_ub[i,:j].dot(self.max_or_min_W1(i, j, mode, 0)) + self.A_ub[i, j+1:].dot(self.max_or_min_W1(i, j, mode, 1)) if j!=0 else self.A_ub[i, j+1:].dot(self.max_or_min_W1(i, j, mode, 1))

    def check_W1(self, i, j):
      b1 = (self.b_ub[i] - self.Ax(i, j, np.min))/self.A_ub[i][j]
      print('{:.0f}x{:.0f}'.format(self.A_ub[i][j], j), '<', self.b_ub[i], '-', self.Ax(i,j,np.min), 'X')
      print('x{:.0f}'.format(j), '<', b1)
      print('x{:.0f}'.format(j), 'in({:.0f},{:.0f})'.format(self.Xvar[j][0], self.Xvar[j][1]))
      if (self.Xvar[j][0] < b1) & (b1>0) & (self.Xvar[j][1]>=b1): 
          print('Отсев')
          self.W1_flag = 1
          if (b1 - int(b1)>0):
              self.Xvar[j][0] = int(b1)+1
          else:
              self.Xvar[j][0] = int(b1)
          print("Новые ограниечения", 'x{:.0f}'.format(j), 'in({:.0f},{:.0f})'.format(self.Xvar[j][0], self.Xvar[j][1]))

    def filter_W1(self):
      self.W1_flag = 0
      for j in range(self.A_ub.shape[1]): # переменная по которой идем
          print("переменная", j)
          for i in range(self.A_ub.shape[0]): # уравнение, которое берем
              print("уравенение", i)
              self.check_W1(i,j)

    def W1(self):
      if not self.stop_point():
          print('----------------------------W1----------------------------------')
          if self.W2_flag == 1:
              self.W2_flag = 0
              self.W1_flag = 1
          else: 
              raise NameError('Error')
          k = 0
          while (self.W1_flag == 1) & (k<1000) & (not self.stop_point()):
              print("КВ-ВО ИТЕРАЦИЙ W1", k)
              self.filter_W1()
              k+=1
      else:
          pass

    def max_func(self):
      return sum([self.cost[i]*Xvar[i][1] if self.cost[i]>0 else self.cost[i]*Xvar[i][0] for i in range(len(self.cost))])


    def min_func(self):
      return sum([self.cost[i]*Xvar[i][0] if self.cost[i]>0 else self.cost[i]*Xvar[i][1] for i in range(len(self.cost))])

    def max_or_min_W2(self, i, mode, flag=0):
      if (flag):
          return [np.max(self.Xvar[i+1+t]) if self.cost[i] < 0 else mode(self.Xvar[i+1+t]) for t in range(len(self.cost[i+1:]))]
      else: 
          return [np.max(self.Xvar[t]) if self.cost[i] < 0 else mode(self.Xvar[t]) for t in range(len(self.cost[:i]))]

    def Cx(self, i, mode=None):
      return self.cost[:i].dot(self.max_or_min_W2(i, mode, 0)) + self.cost[i+1:].dot(self.max_or_min_W2(i, mode, 1)) if i!=0 else self.cost[i+1:].dot(self.max_or_min_W2(i, mode, 1))
  

    def check_W2(self, i):
      b1 = (self.f - self.Cx(i, np.min))/self.cost[i]
      print('{:.0f}x{:.0f}'.format(self.cost[i], i), '>', self.f, '-', self.Cx(i, np.min), 'X')
      print('x{:.0f}'.format(i), '>', b1)
      print('x{:.0f}'.format(i), 'in({:.0f},{:.0f})'.format(self.Xvar[i][0], self.Xvar[i][1]))
      if (self.Xvar[i][1] > b1) & (b1>=0)  & (self.Xvar[i][0]<=b1):
          print('Отсев')
          self.W2_flag = 1
          self.Xvar[i][1] = int(b1)
          print("Новые ограниечения", 'x{:.0f}'.format(i), 'in({:.0f},{:.0f})'.format(self.Xvar[i][0], self.Xvar[i][1]))

    def filter_W2(self):
      for i in range(self.cost.shape[0]): # переменная, которую берем
          print("переменная", i)
          self.check_W2(i)


    def W2(self):
      if not self.stop_point():
          print('----------------------------W2----------------------------------')
          if self.W1_flag == 1: 
              raise NameError('Error')
          self.f = 1/2*(self.min_func() + self.max_func())
          k = 0
          while (self.W2_flag == 0) & (k<1000) & (not self.stop_point()): 
              print("КВ-ВО ИТЕРАЦИЙ W2", k)
              self.filter_W2()
              self.f = 1/2*(self.f + self.min_func())
              k+=1
      else:
          pass


    def stop_point(self):
       return sum([self.Xvar[i][0] == self.Xvar[i][1] for i in range(self.Xvar.shape[1])]) == self.Xvar.shape[1]


    def main(self):
      k = 0
      while (not self.stop_point()) & (k<1000):
          print("--------------------------ИТЕРАЦИЯ----------------------------------------:", k)
          self.W1()
          self.W2()
          k+=1
      X = [Xvar[i][0] for i in range(Xvar.shape[0])]
      return X

In [0]:
instance = PAV(C, A_ub, b_ub, Xvar)

In [0]:
X_opt = instance.main()
print(X_opt)

Z = Z1 +Z2
print(len(Z[0])) 

Cost = np.dot(X_opt, C)
V1 = np.dot(X_opt[0:22], Z1[0])
V2 = np.dot(X_opt[0:22], Z2[0])
print(V1, V2)
print(Cost)

--------------------------ИТЕРАЦИЯ----------------------------------------: 0
----------------------------W1----------------------------------
КВ-ВО ИТЕРАЦИЙ W1 0
переменная 0
уравенение 0
1x0 < 220 - 1.0 X
x0 < 219.0
x0 in(0,1)
уравенение 1
0x0 < 240 - 2.0 X
x0 < inf
x0 in(0,1)
уравенение 2
0x0 < 140 - 2.0 X
x0 < inf
x0 in(0,1)
уравенение 3
0x0 < 200 - 2.0 X
x0 < inf
x0 in(0,1)
уравенение 4
0x0 < 50 - 51.0 X
x0 < -inf
x0 in(0,1)
уравенение 5
0x0 < 60 - 24.0 X
x0 < inf
x0 in(0,1)
уравенение 6
0x0 < 70 - 71.0 X
x0 < -inf
x0 in(0,1)
переменная 1
уравенение 0
0x1 < 220 - 2.0 X
x1 < inf
x1 in(0,1)
уравенение 1
1x1 < 240 - 1.0 X
x1 < 239.0
x1 in(0,1)
уравенение 2
0x1 < 140 - 2.0 X
x1 < inf
x1 in(0,1)
уравенение 3
0x1 < 200 - 2.0 X
x1 < inf
x1 in(0,1)
уравенение 4
0x1 < 50 - 51.0 X
x1 < -inf
x1 in(0,1)
уравенение 5
0x1 < 60 - 24.0 X
x1 < inf
x1 in(0,1)
уравенение 6
0x1 < 70 - 71.0 X
x1 < -inf
x1 in(0,1)
переменная 2
уравенение 0
0x2 < 220 - 2.0 X
x2 < inf
x2 in(0,1)
уравенение 1
0x2 < 240 - 

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:27: RuntimeWarning: divide by zero encountered in double_scalars


x6 in(0,1)
уравенение 5
0x6 < 60 - 24.0 X
x6 < inf
x6 in(0,1)
уравенение 6
0x6 < 70 - 71.0 X
x6 < -inf
x6 in(0,1)
переменная 7
уравенение 0
0x7 < 220 - 2.0 X
x7 < inf
x7 in(0,1)
уравенение 1
0x7 < 240 - 2.0 X
x7 < inf
x7 in(0,1)
уравенение 2
0x7 < 140 - 2.0 X
x7 < inf
x7 in(0,1)
уравенение 3
1x7 < 200 - 1.0 X
x7 < 199.0
x7 in(0,1)
уравенение 4
0x7 < 50 - 51.0 X
x7 < -inf
x7 in(0,1)
уравенение 5
0x7 < 60 - 24.0 X
x7 < inf
x7 in(0,1)
уравенение 6
0x7 < 70 - 71.0 X
x7 < -inf
x7 in(0,1)
переменная 8
уравенение 0
0x8 < 220 - 2.0 X
x8 < inf
x8 in(0,1)
уравенение 1
0x8 < 240 - 2.0 X
x8 < inf
x8 in(0,1)
уравенение 2
0x8 < 140 - 2.0 X
x8 < inf
x8 in(0,1)
уравенение 3
0x8 < 200 - 2.0 X
x8 < inf
x8 in(0,1)
уравенение 4
1x8 < 50 - 50.0 X
x8 < 0.0
x8 in(0,1)
уравенение 5
0x8 < 60 - 24.0 X
x8 < inf
x8 in(0,1)
уравенение 6
0x8 < 70 - 71.0 X
x8 < -inf
x8 in(0,1)
переменная 9
уравенение 0
0x9 < 220 - 2.0 X
x9 < inf
x9 in(0,1)
уравенение 1
0x9 < 240 - 2.0 X
x9 < inf
x9 in(0,1)
уравенение 2
0x9 < 140 - 2

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:27: RuntimeWarning: invalid value encountered in double_scalars


 4
0x2 < 50 - 50.0 X
x2 < nan
x2 in(0,1)
уравенение 5
0x2 < 60 - 22.0 X
x2 < inf
x2 in(0,1)
уравенение 6
0x2 < 70 - 70.0 X
x2 < nan
x2 in(0,1)
переменная 3
уравенение 0
0x3 < 220 - 2.0 X
x3 < inf
x3 in(0,1)
уравенение 1
0x3 < 240 - 2.0 X
x3 < inf
x3 in(0,1)
уравенение 2
0x3 < 140 - 2.0 X
x3 < inf
x3 in(0,1)
уравенение 3
1x3 < 200 - 1.0 X
x3 < 199.0
x3 in(0,1)
уравенение 4
0x3 < 50 - 50.0 X
x3 < nan
x3 in(0,1)
уравенение 5
0x3 < 60 - 22.0 X
x3 < inf
x3 in(0,1)
уравенение 6
0x3 < 70 - 70.0 X
x3 < nan
x3 in(0,1)
переменная 4
уравенение 0
1x4 < 220 - 1.0 X
x4 < 219.0
x4 in(0,1)
уравенение 1
0x4 < 240 - 2.0 X
x4 < inf
x4 in(0,1)
уравенение 2
0x4 < 140 - 2.0 X
x4 < inf
x4 in(0,1)
уравенение 3
0x4 < 200 - 2.0 X
x4 < inf
x4 in(0,1)
уравенение 4
0x4 < 50 - 50.0 X
x4 < nan
x4 in(0,1)
уравенение 5
0x4 < 60 - 22.0 X
x4 < inf
x4 in(0,1)
уравенение 6
0x4 < 70 - 70.0 X
x4 < nan
x4 in(0,1)
переменная 5
уравенение 0
0x5 < 220 - 2.0 X
x5 < inf
x5 in(0,1)
уравенение 1
1x5 < 240 - 1.0 X
x5 < 239.0
x5 in(0

In [0]:
E_A = np.array([[30, 50], [40, 50], [60, 80], [40,80], [60, 100], [30, 70], [25, 35], [35,45]]) #отрезок для равномерного распределения первого пункта добычи сырья
E_B = np.array([[30, 50], [70, 90], [60, 100], [50, 70], [60, 80], [20, 60]]) #отрезок для равномерного распределения второго пункта добычи сырья

alpha = np.array([0.2, 0.4, 0.6, 0.8])  #уровень альфа   
k = 3
print(alpha[0])
scatter = np.array([])
scatter2 = np.array([])
a = np.zeros([4])
b = np.zeros([4])

a = math.sqrt((1-alpha[k])/alpha[k]) #разброс для равномерного
scatter = np.append(scatter, a)
b = math.sqrt(2*math.log(1/alpha[k], math.e)) #разброс для гауссовского
scatter2 = np.append(scatter2, b)
print(scatter)
print(scatter2)

M = np.array([40, 25, 30, 80, 80, 30, 60, 50]) #мат ожидание для гауссовского распределения

#scatter2 = math.sqrt(2*math.log(1/alpha, math.e)) #разброс для гауссовского
#print(scatter2)

0.2
[0.5]
[0.66804723]


**Задача пессимиста**

In [0]:
E_AB = np.concatenate((E_A, E_B), axis = 0 )
print(E_AB)

def koef_p():
  C_U_p = np.array([])
  C_u_p = np.array([])
  e_p = np.zeros([14])
  c_p = np.zeros([8])
  #print(e)
  for i in range(len(E_AB)):
      e_p[i] = (E_AB[i][1] - E_AB[i][0])/2 + scatter
      C_U_p = np.append(C_U_p, e_p[i])
  for j in range(len(M)):
      c_p[j] = M[j] + scatter2      
      C_u_p = np.append(C_u_p, c_p[j])
  c_p = np.concatenate((C_U_p, C_u_p), axis = None)
  return c_p


print(koef_p()) #все коэффициенты целевой функции



[[ 30  50]
 [ 40  50]
 [ 60  80]
 [ 40  80]
 [ 60 100]
 [ 30  70]
 [ 25  35]
 [ 35  45]
 [ 30  50]
 [ 70  90]
 [ 60 100]
 [ 50  70]
 [ 60  80]
 [ 20  60]]
[10.5         5.5        10.5        20.5        20.5        20.5
  5.5         5.5        10.5        10.5        20.5        10.5
 10.5        20.5        40.66804723 25.66804723 30.66804723 80.66804723
 80.66804723 30.66804723 60.66804723 50.66804723]


In [0]:
from scipy.optimize import linprog
res_p = linprog(koef_p(), A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, 
              method='simplex', 
              options={"disp": True}, 
              callback = lambda *x, **kwargs:"tableau" )

print(res_p)

Optimization terminated successfully.
         Current function value: 220629.119216
         Iterations: 19
     con: array([0., 0., 0., 0., 0., 0.])
     fun: 220629.1192157685
 message: 'Optimization terminated successfully.'
     nit: 19
   slack: array([220. , 240. , 140. , 200. ,   0. ,   0. ,  37.5])
  status: 0
 success: True
       x: array([   0. ,    0. ,    0. ,    0. ,    0. ,    0. ,    0. ,    0. ,
         50. ,   10. ,   32.5,    0. ,   50. ,    0. , 1000. , 1200. ,
       1500. ,    0. ,    0. ,    0. ,    0. , 2000. ])


In [0]:
Xvar_p = np.array([[0, 1],
                 [0, 1],
                 [0, 1],
                 [0, 1],
                 [0, 1],
                 [0, 1],
                 [0, 1],
                 [0, 1],
                 [49, 50],
                 [9, 10],
                 [32, 33],
                 [0, 1],
                 [49, 50],
                 [0, 1],
                 [999, 1000],
                 [1199, 1200],
                 [1499, 1500],
                 [0, 1],
                 [0, 1],
                 [0, 1],
                 [0, 1],
                 [1999, 2000]])

In [0]:
V1_p = np.dot(res_p.get('x')[0:22], Z1[0])
V2_p = np.dot(res_p.get('x')[0:22], Z2[0])
                

**Задача оптимиста**

In [0]:
E_AB = np.concatenate((E_A, E_B), axis = 0 )

def koef_o():
  C_U_o = np.array([])
  C_u_o = np.array([])
  e_o = np.zeros([14])
  c_o = np.zeros([8])
  #print(e)
  for i in range(len(E_AB)):
      e_o[i] = (E_AB[i][1] - E_AB[i][0])/2 - scatter
      C_U_o = np.append(C_U_o, e_o[i])
  for j in range(len(M)):
      c_o[j] = M[j] - scatter2
      C_u_o = np.append(C_u_o, c_o[j])
  c_o = np.concatenate((C_U_o, C_u_o), axis = None)
  return c_o


print(koef_o()) #все коэффициенты целевой функции

[ 9.5         4.5         9.5        19.5        19.5        19.5
  4.5         4.5         9.5         9.5        19.5         9.5
  9.5        19.5        39.33195277 24.33195277 29.33195277 79.33195277
 79.33195277 29.33195277 59.33195277 49.33195277]


In [0]:
from scipy.optimize import linprog
res_o = linprog(koef_o(), A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, 
              method='simplex', 
              options={"disp": True}, 
              callback = lambda *x, **kwargs:"tableau" )



print(res.get('x'))

Optimization terminated successfully.
         Current function value: 212822.130784
         Iterations: 20
[   0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
    0.    50.    22.5   70.     0.     0.     0.     0.  1000.  1200.
 1500.  2000. ]


In [0]:
V1_o = np.dot(res_p.get('x')[0:22], Z1[0])
V2_o = np.dot(res_p.get('x')[0:22], Z2[0])
                

**Оформление ответов**

In [0]:
var = ['x_11', 'x_12', 'x_13', 'x_14', 'x_21', 'x_22', 'x_23', 'x_24', 'y_11', 'y_12', 'y_13', 'y_21', 'y_22', 'y_23', 'z_11', 'z_12', 'z_13', 'z_14', 'z_21', 'z_22', 'z_23', 'z_24']

In [0]:
def answ(answ):
  counter_list = list(enumerate(answ, 1))
  for i in counter_list:
    #print(i)
    if i[1] != 0:
      print(var[i[0]-1], ':', math.floor(i[1]))

# **Ответы**

**Чёткая задача** 

In [0]:
print('Общие расходы:', res.get('fun'))
answ(res.get('x'))
print('Объем продукции на первом предприятии:', V1_Ch)
print('Объем продукции на втором предприятии:', V2_Ch)

Общие расходы: 311575.0
y_21 : 50
y_22 : 22
y_23 : 70
z_21 : 1000
z_22 : 1200
z_23 : 1500
z_24 : 2000
Объем продукции на первом предприятии: 0.0
Объем продукции на втором предприятии: 5700.0


In [0]:
print('Общие расходы:', Cost)
answ(X_opt)
print('Объем продукции на первом предприятии:', V1)
print('Объем продукции на втором предприятии:', V2)

Общие расходы: 308546
y_21 : 50
y_22 : 21
y_23 : 70
z_21 : 998
z_22 : 1198
z_23 : 1498
z_24 : 1998
Объем продукции на первом предприятии: 0
Объем продукции на втором предприятии: 5640


**Нечёткая задача**

*Задача пессимиста*

In [0]:
print('Общие расходы:', res_p.get('fun'))
answ(res_p.get('x'))
print('Объем продукции на первом предприятии:', V1_p)
print('Объем продукции на втором предприятии:', V2_p)

Общие расходы: 220629.1192157685
y_11 : 50
y_12 : 10
y_13 : 32
y_22 : 50
z_11 : 1000
z_12 : 1200
z_13 : 1500
z_24 : 2000
Объем продукции на первом предприятии: 3700.0
Объем продукции на втором предприятии: 2000.0


*Задача оптимиста*

In [0]:
print('Общие расходы:', res_o.get('fun'))
answ(res_o.get('x'))
print('Объем продукции на первом предприятии:', V1_o)
print('Объем продукции на втором предприятии:', V2_o)

Общие расходы: 212822.1307842315
x_12 : 130
y_11 : 50
y_12 : 10
y_22 : 50
z_11 : 1000
z_12 : 1200
z_13 : 1500
z_24 : 2000
Объем продукции на первом предприятии: 3700.0
Объем продукции на втором предприятии: 2000.0
